
services:
  app:
    build: .
    container_name: "llm_tools"
    env_file:
      - .env
    ports:
      - "7016:7016"
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    restart: unless-stopped
