[project]
name = "llm-tools-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
    "src/core"
]

[tool.uv.sources]
core = { workspace = true }
